language: python
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - pip install coveralls
script:
  - coverage run --omit=*/site-packages/*,*view* 5
after_success:
  - coveralls
