language: python
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - pip install coveralls
script:
  - coverage run main.py TextGame --size 3 --white ai:3
after_success:
  - coveralls
