language: python
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - pip install coveralls
  - pip install codecov
script:
  - coverage run --omit=*/site-packages/*,*view* main.py -g TextGame --size 5 --white ai:3
  - codecov --token=e656c624-cbc3-452f-952b-6cb1355c0ab6
after_success:
  - coveralls
