version: 2
jobs:
  text:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: cd bredon
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install codecov
      - run: python main.py -g TextGame --size 5 --white ai:3
      - run: codecov --token=e656c624-cbc3-452f-952b-6cb1355c0ab6
workflows:
  version: 2
  full:
    jobs:
      - text
