version: 2
jobs:
  text:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: python main.py -g TextGame --size 5 --white ai:3
  view:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: python view-test.py
workflows:
  version: 2
  full:
    jobs:
      - text
